### ISSUE TITLE
any dataset to demo?

### ISSUE THREAD

**Issue by andyyuan78** [ashkonf/PageRank#1]

**Comment by ashkonf** [comment]
Thanks for reminding me to add one. I'll upload one some time this week. 

Let me know if there's some specific type of data set or subject domain you're interested in and I'll see if I can find a data set that fits what you're looking for.

**Comment by andyyuan78** [comment]
waiting your update

**Comment by ashkonf** [comment]
I just uploaded a demo, and added a blurb to the Readme describing it. Hope it helps!

**Comment by andyyuan78** [comment]
great!
