### ISSUE TITLE
ImportError: No module named 'pranker'

### ISSUE THREAD

**Issue by davidfa94** [ashkonf/PageRank#2]
Hi, I try to import the module 'pagerank' using pip but I get the error message in the title. Trying to import 'pranker' gets me another error saying no such module exists. Any solutions?
Thanks

**Comment by ashkonf** [comment]
This module isn't implemented as a library downloadable by pip. It consists primarily of just a single file you can copy into your project.

**Comment by davidfa94** [comment]
Alright! Problem solved. Thank you @ashkonf

**Comment by mondynihilist** [comment]
i'm sorry. what is the meaning copy into your project ? i dont understand

**Comment by ashkonf** [comment]
Copying this repo's source files into your project directory.
