### ISSUE TITLE
Problem with textrank import

### ISSUE THREAD

**Issue by DavidCabello** [ashkonf/PageRank#3]
Hello, Im having problems running the textrank.py file. When I try to run it, it says: No module named 'nltk.tokenize'. I already installed the nltk module and I dont know what to do now

**Comment by ashkonf** [comment]
Hi David, unfortunately I'm not sure I can debug this from afar. As far as I can tell the tokenize module is still a part of the current nltk distribution (https://github.com/nltk/nltk/tree/develop/nltk/tokenize). Is it possible you installed nltk before it was added? It's possible updating nltk could fix the issue but that's really a shot in the dark.

**Comment by robertiamonico** [comment]
hello i thank you for your pagerank program but i ran it in python 2 and python 3 but i still get th error in the attachment belwo, which i hope you will be able to to see it says error no attribute for object sort and not sure in which file or what is the fix


![github pagerank error](https://user-images.githubusercontent.com/49798411/56447375-e4effd00-62d5-11e9-8628-c380b95be1a2.png)

**Comment by ashkonf** [comment]
I think this was resolved in issue #4!
