### ISSUE TITLE
attribute error series object has no attribute sort

### ISSUE THREAD

**Issue by robertiamonico** [ashkonf/PageRank#4]
hello i thank you for your pagerank program but i ran it in python 2 and python 3 but i still get th error in the attachment below, which i hope you will be able to to see it says error no attribute for object sort and not sure in which file or what is the fix

![github pagerank error](https://user-images.githubusercontent.com/49798411/56447481-a0189600-62d6-11e9-953f-5a934fd369b9.png)

**Comment by robertiamonico** [comment]
line 79 in textrank.py
changed from .sort to .sort_values
it ran for the cinderalla file but i got unicode error ..for the other files
but i think the fix is decode.("utf-8")..i have to check my notes cuz i had this error in another project b4 in python 3

but it ran fully with no errors in python 2.7 there are no unicode errors

**Comment by robertiamonico** [comment]
for python 3
line 104 add  after the open() inside the () encoding='utf-8' like so
document = open(filePath,encoding='utf-8').read()

**Comment by ashkonf** [comment]
Gotcha, that makes a lot of sense. Thanks Robert! Sorry for the delay here.
