### ISSUE TITLE
Adding node links in __ensureRowsPositive

### ISSUE THREAD

**Issue by anathash** [ashkonf/PageRank#5]
https://github.com/ashkonf/PageRank/blob/60d4c6e9aca9bf47413b974da2f4cb20fec4b809/pagerank.py#L36

Hello,
Thanks you very much for contributing this program for wide use. Going over the '__ensureRowsPositive' method it appears as though you are adding links between node for sink nodes. Doesn't this change the structure of the network?

**Comment by ashkonf** [comment]
Hi Anathash, I'm glad you found it useful. That's correct in some ways an incorrect in others. You're right that I'm adding equally weighted outgoing edges from sink nodes to all other nodes, which does change the network at that stage. This is done to avoid divide by zero errors in __normalizeRows. However, this doesn't ultimately change the algorithm's outcome. Once the random surfer probabilities are added, creating edges between all nodes and all other nodes, the impact of having originally added those sink node edges disappears, and the sink node edges become equivalent to random surfer edges.

**Comment by anathash** [comment]
Got it, thanks :)
