### ISSUE TITLE
What's the meaning of 'rsp' argument in function power_iteration()?

### ISSUE THREAD

**Issue by YeeKayy** [ashkonf/PageRank#6]
I'm confused that the description of ‘rsp’ argument in power_iteration（）is same as that of 'transition_weights' .
I assumed that this is a careless mistake. So, what is the real meaning of ‘rsp’ argument?

**Comment by ashkonf** [comment]
It's the "random surfer probability" (see https://www.math.cmu.edu/users/pmelsted/papers/pagerank.pdf)
